from django.urls import path
from .views import (
    ConversationCreateView, 
    ConversationListView,
    MessageCreateView,
    MessageListView,
    MessageUpdateView,
    MessageDeleteView,
    UnreadCountView,
    AddMemberView,
    RemoveMemberView,
    LeaveGroupView,
    TransferOwnershipView,
    DeleteGroupView,
    RenameGroupView,
    GroupDetailsView,
    MessageSearchView,
    MessageReactionView,
    PinMessageView,
    PinnedMessagesView,
)

urlpatterns = [
    path("conversations/", ConversationCreateView.as_view(), name="create_conversation"),
    path("conversations/list/", ConversationListView.as_view(), name="list_conversations"),
    path("messages/", MessageCreateView.as_view(), name="send_message"),
    path(
    "conversations/<int:conversation_id>/messages/",
    MessageListView.as_view(),
    name="conversation_messages",
    ),
    path(
        "messages/<int:message_id>/",
        MessageUpdateView.as_view(),
        name="edit_message",
    ),
    path(
    "messages/<int:message_id>/delete/",
    MessageDeleteView.as_view(),
    name="delete_message",
    ),
    path("unread-counts/", UnreadCountView.as_view()),

    path(
    "conversations/<int:conversation_id>/members/",
    AddMemberView.as_view(),
    name="add-member"
),
path(
    "conversations/<int:conversation_id>/members/<int:user_id>/",
    RemoveMemberView.as_view(),
    name="remove-member",
),
path(
    "conversations/<int:conversation_id>/leave/",
    LeaveGroupView.as_view(),
    name="leave-group",
),
path(
    "conversations/<int:conversation_id>/transfer-ownership/",
    TransferOwnershipView.as_view(),
    name="transfer-ownership",
),
path(
    "conversations/<int:conversation_id>/delete-group/",
    DeleteGroupView.as_view(),
    name="delete-group",
),
path(
    "conversations/<int:conversation_id>/transfer-ownership/",
    TransferOwnershipView.as_view(),
    name="transfer-ownership",
),
path(
    "conversations/<int:conversation_id>/delete-group/",
    DeleteGroupView.as_view(),
    name="delete-group",
),
path(
    "conversations/<int:conversation_id>/rename/",
    RenameGroupView.as_view(),
    name="rename-group",
),
path(
    "conversations/<int:conversation_id>/details/",
    GroupDetailsView.as_view(),
    name="group-details",
),
path(
    "conversations/<int:conversation_id>/search/",
    MessageSearchView.as_view(),
    name="search-messages",
),
path(
    "messages/<int:message_id>/react/",
    MessageReactionView.as_view(),
    name="react_to_message",
),
path(
    "messages/<int:message_id>/pin/",
    PinMessageView.as_view(),
    name="pin_message",
),
path(
    "conversations/<int:conversation_id>/pinned/",
    PinnedMessagesView.as_view(),
    name="pinned_messages",
),
]