# Generated by Django 6.0.5 on 2026-06-02 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagereceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together={('conversation', 'user')},
        ),
    ]
