# Generated by Django 6.0.5 on 2026-06-18 13:13

import chat.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_forwarded_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=chat.storage.AttachmentStorage(), upload_to='chat_attachments/'),
        ),
    ]
