# Generated by Django 6.0.5 on 2026-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('reply', 'Reply'), ('mention', 'Mention'), ('group', 'Group'), ('pin', 'Pin'), ('mention', 'Mention')], max_length=20),
        ),
    ]
